name: Download OneDrive File

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate OneDrive direct download link
      id: generate_link
      run: |
        # 原始OneDrive分享链接
        ONEDRIVE_SHARE_LINK='https://onedrive.live.com/?cid=5A43C412343CDA85&id=5A43C412343CDA85%21se8ce2449639945618af8d0d0106cd011&parId=root&o=OneUp'
        # 提取文件ID
        FILE_ID=$(echo $ONEDRIVE_SHARE_LINK | grep -oP '(?<=id=)[^&]*')
        # 生成直接下载链接
        DIRECT_DOWNLOAD_LINK="https://onedrive.live.com/download?resid=$FILE_ID"
        echo "::set-output name=link::$DIRECT_DOWNLOAD_LINK"

    - name: Download OneDrive file
      env:
        DIRECT_DOWNLOAD_LINK: ${{ steps.generate_link.outputs.link }}
      run: |
        mkdir -p downloaded_files
        wget "$DIRECT_DOWNLOAD_LINK" -O downloaded_files/filename.ext

    - name: Add and commit files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add downloaded_files
        git commit -m 'Add downloaded file from OneDrive'
        git push
