name: Extract DUMP from ROM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract-dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download Dumpyara
      run: |
        wget https://github.com/sample/dumpyara/archive/refs/heads/main.zip -O dumpyara.zip
        unzip dumpyara.zip -d dumpyara

    - name: Download ROM file
      run: |
        wget https://example.com/path/to/your/rom.zip -O rom.zip

    - name: Extract ROM file
      run: |
        mkdir rom
        unzip rom.zip -d rom

    - name: Run Dumpyara
      run: |
        cd dumpyara/dumpyara-main
        python dumpyara.py -p ../../rom

    - name: Upload DUMP directory
      uses: actions/upload-artifact@v2
      with:
        name: dump-directory
        path: dumpyara/dumpyara-main/output # Adjust the path to where the DUMP directory is stored
